@startuml
title Logical View

class WebSession {
    -user : User

    +register() : HTMLResponse
    +login() : HTMLResponse
    +logout() : HTMLResponse
    +addWebCheck() : HTMLResponse
    +removeWebCheck(WebCheck webcheck) : HTMLResponse
    +changeFrequency(WebCheck webcheck) : HTMLResponse
}

class WebCheck {
    -websiteString : string
    -interval : int
    -notifiers : Notifier[]

    +getWebsiteUpdates() : void
    +addNotifier(Notifier notifier) : void
    +removeNotifier(Notifier notifier) : void
    +changeFrequency(int interval) : void
}
class User {
    -username : string
    -email : string
    -webChecks : WebCheck[]

    +getWebChecks() : WebCheck[]
    +addWebCheck(WebCheck webcheck) : void
    +removeWebCheck(WebCheck webcheck) : void

}
class DBManager {
    -dbConnection : boolean

    +loginUser(User user) : User
    +registerUser(string name, ) : User
    +updateUser(User user) : void
}
class Notifier {
    +notificationChannel : string

    +sendNotification() : void
    +setNotificationChannel(string channel) : void
}

class WebCheckService {
    executeAllWebChecks() : void
}

WebSession "1" -- "1" User : > has
WebSession "1" -- "1" DBManager : > uses
WebCheck "1" -- "0...*" Notifier : > has
DBManager *--  User : > creates
User "1" -- "0...*" WebCheck : > has
WebCheckService "1" -- "1" DBManager : > uses
@enduml

@startuml
title Process View

@enduml
