@startuml
skinparam pageMargin 10
skinparam pageExternalColor gray
skinparam pageBorderColor black

class Main
Main "1" o-- "1" webtracker.main.WebsiteMonitor

note "EC=2, AC=2, I=1/2" as N1
N1 .. webtracker.interactions
namespace webtracker.interactions #DDDDDD {
  Main "1" --> "1" webtracker.interactions.BackgroundWebChecker
  Main "1" --> "1" webtracker.interactions.InputHandler
  webtracker.interactions.BackgroundWebChecker "1" --> "1" webtracker.main.WebsiteMonitor
  webtracker.interactions.InputHandler "1" --> "1" webtracker.main.WebsiteMonitor
}

note "EC=1, AC=3, I=1/4" as N2
N2 .. webtracker.main
namespace webtracker.main #DDDDDD {
  webtracker.main.User "1" *-- "0..*" webtracker.subscription.Subscription
  webtracker.main.WebsiteMonitor "1" *-- "0..*" webtracker.main.User
}

note "EC=0, AC=1, I=0" as N3
N3 .. webtracker.subscription
namespace webtracker.subscription #DDDDDD {
  webtracker.subscription.Subscription "1" *-- "1" webtracker.subscription.Website: creates
  webtracker.subscription.Subscription "1"  *-- "1" webtracker.subscription.Notification: creates

}

@enduml
